### ISSUE TITLE
Couldn't find /citadel.org/Tzfile/Europe/Amsterdam

### ISSUE THREAD

**Issue by rolfdeenen** [corinis/synckolab#3]
Hi. I am running synckolab to sync my local Thunderbird installation with my Citadel server. This works sometimes. I thought it stumbled over all-day events, but when I am running it now it halts on a random event. The Thunderbird error console gives me the following error:

Timestamp: 04-10-15 10:13:23
Error: Couldn't find /citadel.org/Tzfile/Europe/Amsterdam
Source File: file:///home/rolf/.thunderbird/xlrc9jtm.default/extensions/%7Be2fda1a4-762b-4020-b5ad-a41df1933103%7D/components/calTimezoneService.js
Line: 18

Restarting Thunderbird and synching again will still stall over the same event. I also notice that the previously synced entries have the status "No change" but the description is now followed by a line: NaN-NaN-NaNTNaN:NaN:NaN
![screenshot from 2015-10-04 10 25 46](https://cloud.githubusercontent.com/assets/4473038/10267062/77796418-6a82-11e5-9fc5-3b9f16526326.png)

Here are all the error mesages. Ignore the gmail account. I have a Citadel IMAP account configured which is hidden by the other windows:
![screenshot from 2015-10-04 10 28 44](https://cloud.githubusercontent.com/assets/4473038/10267066/d7d5b276-6a82-11e5-9092-b06debf29563.png)

**Comment by corinis** [comment]
Hi, maybe you can attach/mail me one event that has an issue? Just the attachment should be enough in that case - (you can also send me the *.eml file - but that contains sensitive information like email addresses - so you might want to mail it to skbugs(at)corinis,net ) from what I see espcially the last one (53215c..) looks like the one with the issue.

**Comment by rolfdeenen** [comment]
Hi Coronis. I have been investigating further and by now it seems that initial sync goes well but as soon as I update an event the following sync stumbles over that event. It doesn't seem to matter if the change is made in Thunderbird/Lighting or on Citadel's calendar. I am using Ubuntu 15.04 with Thunderbird 38.2.0, Lightning 4.0.2.1 and Kolabsync 3.1.6 . I e-maild an event that I have updated on the Citadel server (I added a description) . Now syncing halts on this event. The status of syncing this event keps saying: "checking". Uploading doesn't work: It keeps saying that "Something went really wrong, and we can't process that file", even when I turn it into a pdf.

**Comment by rolfdeenen** [comment]
I did notice the event has the following "wierd"(seems to me) information in it. Could this have something to do with it?

TZID=3D/citadel.org/Tzfile/Europe/Amsterdam:20151024T090000

**Comment by corinis** [comment]
Hi, yes that is the "problematic" field. I will check the sync and add a workaround to adapt it when trying to convert to a lighting event

**Comment by rolfdeenen** [comment]
Or, should Citadel use another value in this field? I am unfamiliar with vcalendar and the "allowed" values. Just to made sure I posted a question about this on the Citadel Support forum/room on uncensored.citadel.org . No answer at this moment...

**Comment by corinis** [comment]
no, I think citadel is correct there....

**Comment by rolfdeenen** [comment]
Thanks!

2015-10-11 0:02 GMT+02:00 Niko notifications@github.com:
